[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
vault = "BGQ6npBd8Fv4DWUjgNtm149Yh1VNR2yseaGVSjs5ksrB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test2 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/position.ts"
